In [ ]:
# Import libraries
import keras
from keras.datasets import mnist
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Import datasets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

11501568/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [ ]:
# Reshape and normalize
X_train = x_train.reshape(-1, 28*28)/255.0
X_test = x_test.reshape(-1, 28*28)/255.0
print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)


In [ ]:
# Transform to Odd and Even the output layer
y_train_transformed = y_train.copy()
y_test_transformed = y_test.copy()
for i in range(len(y_train)):
  y_train_transformed[i] = y_train[i] % 2

for i in range(len(y_test)):
  y_test_transformed[i] = y_test[i] % 2

In [ ]:
from sklearn.svm import SVC

# Polynomial Kernel
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train_transformed)

y_pred_poly = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print("Polynomial Kernel\nConfusion Matrix:")
print(confusion_matrix(y_test_transformed, y_pred_poly))
print("\nClassification report:")
print(classification_report(y_test_transformed, y_pred_poly))

Polynomial Kernel
Confusion Matrix:
[[4462  464]
 [  91 4983]]

Classification report:
              precision    recall  f1-score   support

           0       0.98      0.91      0.94      4926
           1       0.91      0.98      0.95      5074

    accuracy                           0.94     10000
   macro avg       0.95      0.94      0.94     10000
weighted avg       0.95      0.94      0.94     10000



In [ ]:
from sklearn.svm import SVC

# Gaussian Kernel
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train_transformed)

y_pred_rbf = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print("Gaussian Kernel\nConfusion Matrix:")
print(confusion_matrix(y_test_transformed, y_pred_rbf))
print("\nClassification report:")
print(classification_report(y_test_transformed, y_pred_rbf))

Gaussian Kernel
Confusion Matrix:
[[4861   65]
 [  71 5003]]

Classification report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4926
           1       0.99      0.99      0.99      5074

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000



In [ ]:
from sklearn.svm import SVC

# Sigmoid Kernel
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train_transformed)

y_pred_sig = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print("Sigmoid Kernel\nConfusion Matrix:")
print(confusion_matrix(y_test_transformed, y_pred_sig))
print("\nClassification report:")
print(classification_report(y_test_transformed, y_pred_sig))

Sigmoid Kernel
Confusion Matrix:
[[3404 1522]
 [1534 3540]]

Classification report:
              precision    recall  f1-score   support

           0       0.69      0.69      0.69      4926
           1       0.70      0.70      0.70      5074

    accuracy                           0.69     10000
   macro avg       0.69      0.69      0.69     10000
weighted avg       0.69      0.69      0.69     10000



In [ ]:
# KNN model
import numpy as np
import operator 
from operator import itemgetter
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
from mnist import MNIST

# The Euclidean Distance between two points
def euc_dist(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2))

# KNN class
class KNN:
    def __init__(self, K=3):
        self.K = K
    def fit(self, x_train, y_train):
        self.X_train = x_train
        self.Y_train = y_train

    def predict(self, X_test):
        predictions = [] 
        for i in range(len(X_test)):
            dist = np.array([euc_dist(X_test[i], x_t) for x_t in   
            self.X_train])
            dist_sorted = dist.argsort()[:self.K]
            neigh_count = {}
            for idx in dist_sorted:
                if self.Y_train[idx] in neigh_count:
                    neigh_count[self.Y_train[idx]] += 1
                else:
                    neigh_count[self.Y_train[idx]] = 1
            sorted_neigh_count = sorted(neigh_count.items(),    
            key = operator.itemgetter(1), reverse=True)
            predictions.append(sorted_neigh_count[0][0]) 
        return predictions

In [ ]:
def main():

    testDataRange = 2000

    # train: X_train, y_train_transformed 
    # test: X_test, y_test_transformed

    print("X_train dataset shape: " + str(X_train.shape) + "\t| y_train dataset shape: "  + str(y_train_transformed.shape))
    print("X_test dataset shape: " + str(X_test.shape) + "\t| y_test dataset shape: "  + str(y_test_transformed.shape))

    kVals = [1, 3]
    for k in kVals:
        model = KNN(K = k)
        model.fit(X_train, y_train_transformed)
        x_test_mini = X_test[0:testDataRange,:]
        y_test_mini = y_test_transformed[0:testDataRange,]
        print("\nChanged test dataset shape")
        print("New X_test dataset shape: " + str(x_test_mini.shape) + "\t| New y_test dataset shape: "  + str(y_test_mini.shape))
        pred = model.predict(x_test_mini)
        accuracy = accuracy_score(y_test_mini, pred)
        print("K = " + str(k)+" | Accuracy: " + str(accuracy))

if __name__ == "__main__":
    main() 

X_train dataset shape: (60000, 784)	| y_train dataset shape: (60000,)
X_test dataset shape: (10000, 784)	| y_test dataset shape: (10000,)

Changed test dataset shape
New X_test dataset shape: (2000, 784)	| New y_test dataset shape: (2000,)
K = 1 | Accuracy: 0.981

Changed test dataset shape
New X_test dataset shape: (2000, 784)	| New y_test dataset shape: (2000,)
K = 3 | Accuracy: 0.9815


In [ ]:
# Nearest centroid model

# Import libraries
import keras
from keras.datasets import mnist
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.neighbors import NearestCentroid

In [ ]:
metric_name = ['euclidean', 'manhattan']
res_dict = {}
for metric in metric_name:
  # define model
  model = NearestCentroid(metric=metric)

  # define model evaluation method
  cv = RepeatedStratifiedKFold(n_splits=60, n_repeats=5, random_state=1)

  # evaluate model
  scores = cross_val_score(model, X_train, y_train_transformed, scoring='accuracy', cv=cv, n_jobs=-1)

  name = metric

  # summarize result
  print("Name: " + name)
  print('Mean Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

  res_dict[name] = mean(scores)

Name: euclidean
Mean Accuracy: 0.808 (0.012)
Name: manhattan
Mean Accuracy: 0.792 (0.012)


In [ ]:
# make predictions with a nearest centroid model on the test dataset
from sklearn.datasets import make_classification
from sklearn.neighbors import NearestCentroid
from sklearn.metrics import classification_report

X = X_train
y = y_train_transformed
y_test = y_test_transformed

# define model
model = NearestCentroid()

# fit model
model.fit(X, y)

# make a prediction
y_pred = model.predict(X_test)

# Printing Accuracy on Training and Test sets
print(f"Training Set Score : {model.score(X, y) * 100} %")
print(f"Test Set Score : {model.score(X_test, y_test) * 100} %")
 
# Printing classification report of classifier on the test set set data
print(f"Model Classification Report : \n{classification_report(y_test, model.predict(X_test))}")

Training Set Score : 80.84666666666666 %
Test Set Score : 80.25999999999999 %
Model Classification Report : 
              precision    recall  f1-score   support

           0       0.83      0.75      0.79      4926
           1       0.78      0.85      0.81      5074

    accuracy                           0.80     10000
   macro avg       0.81      0.80      0.80     10000
weighted avg       0.81      0.80      0.80     10000



In [ ]:
# SVM Model

from sklearn import svm
from sklearn.model_selection import GridSearchCV

def svc_param_selection(X, y):
    Cs = [0.1]
    # gammas = [0.01, 0.1, 1]
    kernels = ['linear', 'poly', 'rbf']
    param_grid = {'kernel': kernels, 'C': Cs}
    svc = svm.SVC(shrinking=True, random_state=50)
    grid_search = GridSearchCV(svc, param_grid, verbose=2, cv=3, n_jobs=-1)  
    grid_search.fit(X, y)
    # grid_search.best_params_
    return grid_search

import pandas as pd

grid_search = svc_param_selection(X_train, y_train_transformed)
grid_search.best_params_
pd.DataFrame(grid_search.cv_results_)

Fitting 3 folds for each of 3 candidates, totalling 9 fits


/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:705: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0    1109.509010     18.693400  ...        0.002972                3
1     480.971471      8.551070  ...        0.000995                1
2     518.584412     23.081724  ...        0.000357                2

[3 rows x 13 columns]

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

def svc_param_selection(X, y):
    Cs = [1]
    # gammas = [0.01, 0.1, 1]
    kernels = ['linear', 'poly', 'rbf']
    param_grid = {'kernel': kernels, 'C': Cs}
    svc = svm.SVC(shrinking=True, random_state=50)
    grid_search = GridSearchCV(svc, param_grid, verbose=2, cv=3, n_jobs=-1)  
    grid_search.fit(X, y)
    print(grid_search.best_params_)
    return grid_search

import pandas as pd

grid_search = svc_param_selection(X_train, y_train_transformed)
print(grid_search.best_params_)
pd.DataFrame(grid_search.cv_results_)

Fitting 3 folds for each of 3 candidates, totalling 9 fits
{'C': 1, 'kernel': 'rbf'}
{'C': 1, 'kernel': 'rbf'}


mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0    5087.442578    403.196876  ...        0.002736                3
1     396.389390      4.081429  ...        0.000755                2
2     413.289100      5.601927  ...        0.000589                1

[3 rows x 13 columns]

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

def svc_param_selection(X, y):
    Cs = [10]
    # gammas = [0.01, 0.1, 1]
    kernels = ['poly', 'rbf']
    param_grid = {'kernel': kernels, 'C': Cs}
    svc = svm.SVC(shrinking=True, random_state=50)
    grid_search = GridSearchCV(svc, param_grid, verbose=2, cv=3, n_jobs=-1)  
    grid_search.fit(X, y)
    # print(grid_search.best_params_)
    return grid_search

import pandas as pd

grid_search = svc_param_selection(X_train, y_train_transformed)
grid_search.best_params_
pd.DataFrame(grid_search.cv_results_)

Fitting 3 folds for each of 2 candidates, totalling 6 fits
[CV] END ..................................C=10, kernel=poly; total time=18.4min
[CV] END ..................................C=10, kernel=poly; total time=19.1min
[CV] END ..................................C=10, kernel=poly; total time=19.5min
[CV] END ...................................C=10, kernel=rbf; total time=23.8min
[CV] END ...................................C=10, kernel=rbf; total time=14.0min
[CV] END ...................................C=10, kernel=rbf; total time=13.4min


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0     987.314135     30.631078       153.242518       13.667000      10   
1     910.147821    256.057295       113.316875       30.261559      10   

  param_kernel                       params  split0_test_score  \
0         poly  {'C': 10, 'kernel': 'poly'}            0.98410   
1          rbf   {'C': 10, 'kernel': 'rbf'}            0.98775   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0             0.9850            0.98310         0.984067        0.000776   
1             0.9875            0.98675         0.987333        0.000425   

   rank_test_score  
0                2  
1                1

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

def svc_param_selection(X, y):
    Cs = [10]
    # gammas = [0.01, 0.1, 1]
    kernels = ['linear']
    param_grid = {'kernel': kernels, 'C': Cs}
    svc = svm.SVC(shrinking=True, random_state=50)
    grid_search = GridSearchCV(svc, param_grid, verbose=2, cv=3, n_jobs=-1)  
    grid_search.fit(X, y)
    # print(grid_search.best_params_)
    return grid_search

import pandas as pd

grid_search = svc_param_selection(X_train, y_train_transformed)
grid_search.best_params_
pd.DataFrame(grid_search.cv_results_)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
